### ISSUE TITLE
[Suggestion] Use more unique foldernames

### ISSUE THREAD

**Issue by xenoflot** [Siriuo/wirenut-compiler#2]
It looks like you're using "done" and "mods" as your working folders. Those are so generic that I actually already had folders with those names as subfolders :)

Perhaps use WNC_done and WNC_todo?

**Comment by Siriuo** [comment]
The mods folder is there due to the way it compiles the zips. As solder requires the mods to be inside of the zip in order to extract correctly. I will work on a tidier solution for the folder structure

**Comment by Siriuo** [comment]
I have tidied up the zips format. It will now create a tmp directory for working then once everything has been done all jar files are moved back to the original directory.
