### ISSUE TITLE
Unhandled IO exception

### ISSUE THREAD

**Issue by xenoflot** [Siriuo/wirenut-compiler#3]
How do I make visual studio show line numbers? This line in MainFirm.vb errored:
System.IO.File.Move(modFile, openPath + "/mods/" + fileName + fileExtension)

Silly me didn't check to see what was in the source folder before I ran WNC. Does WNC remove jars from the source folder when it processes them? Right now, my source folder contains only 1 jar and the various subfolders.

Looking at the zips... that 1 jar... is inside *every* zip.
Going to do some more testing now.

Debug output
------
Zipped File
Moved To Done Folder
Updated Progress Bar
Moved To Mods Folder
Exception thrown: 'System.IO.IOException' in mscorlib.dll
Zipped File
Moved To Done Folder
Updated Progress Bar
Moved To Mods Folder
Zipped File
Moved To Done Folder
Updated Progress Bar
Moved To Mods Folder
Zipped File
Moved To Done Folder
Updated Progress Bar
'Wirenut Compiler.vshost.exe' (CLR v4.0.30319: Wirenut Compiler.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

**Comment by Siriuo** [comment]
Possible that the done folder already has that file. Will do some test and will fix this.

**Comment by xenoflot** [comment]
The mods folder had it. I guess you're just deleting the one file you put in there but not checking to see if it's empty first.

Using a structure like WNC-data/mods and running a preemptive del *.* before starting the batch should solve that (without unintentionally deleting stuff you shouldn't).

**Comment by xenoflot** [comment]
OK, I just tested again with a clean structure this time.
/WNC and /out

With clean folders everywhere, mods only in /WNC, it runs cleanly.
If I put a mod in /WNC/mods then run it, the error occurs and each zip includes it.

**Comment by Siriuo** [comment]
Issue resolved
